
 board: [ "nice_nano" ]
 shield: [ "corne_left", "corne_right" ]
 include:
  - board: nice_nano
    shield: sofle_left nice_view_adapter nice_view

  - board: nice_nano
    shield: sofle_right nice_view_adapter nice_view

  - board: nice_nano
    shield: settings_reset

