include:
  # Cambia SOLO la línea "board:" según tu revisión:
  # - v2: nice_nano
  # - v1: nice_nano@1.0.0

  - board: nice_nano@1.0.0
    shield: sofle_left nice_view_adapter nice_view

  - board: nice_nano@1.0.0
    shield: sofle_right nice_view_adapter nice_view

  - board: nice_nano@1.0.0
    shield: settings_reset
